# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='000', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='endsem_exam_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 31, 11, 9, 27, 470048)),
        ),
        migrations.AddField(
            model_name='course',
            name='midsem_exam_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 31, 11, 9, 27, 470004)),
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_student',
            field=models.ManyToManyField(to='hello_world.Student'),
        ),
    ]
