# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0006_auto_20161104_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='endsem_exam_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 4, 16, 41, 19, 707000)),
        ),
        migrations.AlterField(
            model_name='course',
            name='midsem_exam_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 4, 16, 41, 19, 707000)),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 4, 16, 41, 19, 723000)),
        ),
    ]
