# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0008_auto_20161104_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2016, 11, 5, 21, 48, 42, 582000))),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='course',
            name='endsem_exam_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 21, 48, 42, 582000)),
        ),
        migrations.AlterField(
            model_name='course',
            name='midsem_exam_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 21, 48, 42, 582000)),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 21, 48, 42, 582000)),
        ),
        migrations.AddField(
            model_name='assignmentdeadline',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.Course'),
        ),
    ]
