# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_auto_20161031_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=20)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'feedback', max_length=100)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2016, 11, 1, 16, 27, 20, 350000))),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.FeedbackForm')),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='course',
            name='endsem_exam_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 1, 16, 27, 20, 342000)),
        ),
        migrations.AlterField(
            model_name='course',
            name='midsem_exam_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 1, 16, 27, 20, 342000)),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.Course'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.Question'),
        ),
    ]
