# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello_world', '0007_auto_20161104_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOrInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=b'instructor', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.AlterField(
            model_name='course',
            name='endsem_exam_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 4, 16, 49, 1, 974000)),
        ),
        migrations.AlterField(
            model_name='course',
            name='midsem_exam_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 4, 16, 49, 1, 974000)),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 4, 16, 49, 1, 974000)),
        ),
    ]
